AllCops:
  Include:
    - ./**/*.rb
  Exclude:
    - moduleroot/spec/spec_helper.rb
    - moduleroot/spec/classes/coverage_spec.rb
    - vendor/**/*
    - modules/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# dealbreaker:
Style/TrailingCommaInArguments:
  Enabled: false

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false
