---
.travis.yml:
  includes:
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  allow_failures:
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
Gemfile:
  required:
    ':test':
      - gem: puppetlabs_spec_helper
      - gem: rspec-puppet
        git: https://github.com/rodjek/rspec-puppet.git
      - gem: rspec-puppet-facts
      - gem: rspec-puppet-utils
      - gem: puppet-lint
        git: https://github.com/rodjek/puppet-lint.git
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: metadata-json-lint
      - gem: puppet-blacksmith
        git: https://github.com/voxpupuli/puppet-blacksmith.git
      - gem: voxpupuli-release
        git: https://github.com/voxpupuli/voxpupuli-release-gem.git
      - gem: puppet-strings
        git: https://github.com/puppetlabs/puppetlabs-strings.git
      - gem: rubocop-rspec
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
        require: false
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_140chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
  default_enabled_rake_targets:
  - 'metadata_lint'
  - 'lint'
  - 'syntax'
  - 'spec'

...
