---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':test':
      - gem: rake
      - gem: rspec-puppet
        git: https://github.com/rodjek/rspec-puppet.git
      - gem: puppetlabs_spec_helper
      - gem: metadata-json-lint
      - gem: rspec-puppet-facts
      - gem: rspec
      - gem: puppet-blacksmith
      - gem: rubocop
      - gem: rspec-puppet-utils
      - gem: puppet
        version: ENV['PUPPET_VERSION'] || '~> 3.8.0'
      - gem: rspec-puppet-augeas
      - gem: ruby-augeas
      - gem: puppetlabs_spec_helper
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
...
