---
notifications:
  email: false
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
<%- if !@configs.nil? and @configs.has_key?('addons') -%>
addons:
  <%- if @configs['addons'].has_key?('apt') -%>
  apt:
    <%- if @configs['addons']['apt'].has_key?('sources') -%>
    sources:
      <%- @configs['addons']['apt']['sources'].each do |x| -%>
      - <%= x %>
      <%- end -%>
    <%- end -%>
    <%- if @configs['addons']['apt'].has_key?('packages') -%>
    packages:
      <%- @configs['addons']['apt']['packages'].each do |x| -%>
      - <%= x %>
      <%- end -%>
    <%- end -%>
  <%- end -%>
<%- end -%>
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.4" CHECK=test
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "<%= @configs['secure'] -%>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
